kolplattformen/embedded-api

- lib/children.ts
- lib/index.ts
Hopefully retrieves and parses class mates. I cannot confirm since,
according to Skolplattformen, my daughter has none.
✅ Closes: #7
> feat: 🎸 Classmates

- .gitignore
- README.md
- lib/children.ts
- lib/h2m.d.ts
- lib/index.ts
- lib/news.ts
- lib/parse.test.ts
- lib/parse.ts
- lib/types.ts
- package.json
- run.js
- yarn.lock
...I hope. Becausa, again, my daugther does not have any
✅ Closes: #13
> feat: 🎸 Loads schedule

- .eslintrc.js
- README.md
- lib/index.ts
- lib/parse.test.ts
- lib/parse.ts
- lib/types.ts
- lib/user.ts
- run.js
Returns currrenctly logged in user
✅ Closes: #9
> feat: 🎸 getUser

- README.md
- lib/children.ts
- lib/index.ts
- lib/parse.test.ts
- lib/parse.ts
- lib/types.ts
- run.js
> feat: 🎸 Notifications

- lib/image.ts
- lib/index.ts
- lib/login.test.ts
- lib/types.ts
- run.js
> feat: 🎸 Image

- lib/api.test.ts
- lib/api.ts
- lib/fetcher.test.ts
- lib/fetcher.ts
- lib/parse.test.ts
- lib/parse.ts
- lib/types.ts
- run.js
BREAKING CHANGE: 🧨 api no longer exposes getImage()
> feat: 🎸 Removed getImage() and added .fullImageUrl to NewsItem

- lib/fakeData.ts
Add another news to the list of fake data.
> Add news about programming

- lib/fakeData.ts
Fixes formatting in fakeData.js (also make a new version).
> fix: 🐛 Correct format of fakeData.js

- README.md
Dags att våga ta steget till 1.0.0
BREAKING CHANGE: 🧨 Nä... egentligen inte
> feat: 🎸 Släpp sargen - nu kör vi

- lib/api.ts
- lib/parse.ts
- lib/parseHtml.test.ts
- lib/parseHtml.ts
- run.js
Vissa nyheter small vid parsning. Då det inte var avsikten har smäll-koden bytts ut.
> Fixar för parsning

- lib/routes.ts
GetNewsArchive istf. GetNewsOverview
> feat: 🎸 Alla nyhetsbrev

- lib/api.ts
...för att bättre emulera nätverkstrafik
> feat: 🎸 Fakedata laggar 0.2-1 sekund

- lib/api.ts
Någon får gärna städa upp koden, för jag är rätt kass på typescript, men denna fix verkar gå förbi Stockholms Stads försök till blockering.
> Fix för Stockholms nedstängning av Öppna Skolplattformen

- lib/api.ts
Lade till några saknade headers.
> fix så att man kan läsa data från Skolplattformen... igen

- lib/api.ts
- lib/routes.ts
Denna gör så att bl.a. x-xsrf-token7 fungerar samt lägger till
cachebusting parameter på childcontroller
> fix: 🐛 Fix för login block 24mars

- config.json
> config.json

- lib/api.test.ts
- lib/fakeData.ts
Needed for background app state change in app
> fix: 🐛 Added isAuthenticated to test user

- lib/parse/__tests__/news.test.ts
- lib/parseHtml.test.ts
- lib/parseHtml.ts
Förbättrad parsning av nyhetsbrev. Färre vilda asterisker kvar i texterna
> fix: 🐛 Förbättrad parsning av nyhetsbrev

- lib/api.ts
> fix: 🐛 Silly stockholm stad protection

- lib/api.ts
- package.json
- yarn.lock
> Use base-64 npm package for encoding

- lib/parse/__tests__/news.test.ts
- lib/parse/news.ts
If modified date is missing, publish date will be used
> feat: 🎸 News are sorted, desc, by modified date
